"""empty message

Revision ID: 7f52e39431aa
Revises: dc83483bac91
Create Date: 2020-04-06 11:51:10.698394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f52e39431aa'
down_revision = 'dc83483bac91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('Alter Table "Show" Drop Constraint "Show_pkey";')
    op.execute('ALTER TABLE "Show" ADD PRIMARY KEY (id);')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Show', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Show', 'start_time',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('Show', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('Show', 'id')
    # ### end Alembic commands ###
