"""empty message

Revision ID: f200859e6fb2
Revises: 5c5b867dd29f
Create Date: 2020-04-05 22:18:32.918571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f200859e6fb2'
down_revision = '5c5b867dd29f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('Venue', 'seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    op.execute('UPDATE "Artist" SET seeking_venue = False Where seeking_venue IS NULL;')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
